# Generated by Django 4.1.7 on 2023-05-07 14:11

import ImageSRAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_image', models.ImageField(blank=True, null=True, upload_to=ImageSRAPP.models.file_path)),
            ],
        ),
    ]
