# Generated by Django 4.1.7 on 2023-05-07 18:06

import ImageSRAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSRAPP', '0004_alter_image_table_sr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_table',
            name='lr_image',
            field=models.ImageField(default=True, null=True, upload_to=ImageSRAPP.models.file_path),
        ),
    ]
