# Generated by Django 4.1.7 on 2023-05-08 04:15

import ImageSRAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSRAPP', '0009_image_table_sr_remove_image_table_sr_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LR_Image_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lr_image', models.ImageField(null=True, upload_to=ImageSRAPP.models.file_path)),
            ],
        ),
        migrations.CreateModel(
            name='SR_Image_table_sr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_image', models.ImageField(null=True, upload_to=ImageSRAPP.models.file_path_sr)),
            ],
        ),
    ]
